# permissions for end users to view ducksels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ducksel-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crd-ducksel
    app.kubernetes.io/part-of: crd-ducksel
    app.kubernetes.io/managed-by: kustomize
  name: ducksel-viewer-role
rules:
- apiGroups:
  - api.my.domain
  resources:
  - ducksels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.my.domain
  resources:
  - ducksels/status
  verbs:
  - get
